version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sololeveling
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

  api:
    build: ..
    environment:
      DB_DSN: "postgres://postgres:postgres@db:5432/solo?sslmode=disable"
      JWT_SECRET: "secret"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pg: